name: Linux x86_64

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'

jobs:

  linux:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: sunwalker_box

    steps:
      - name: Clone.
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: Build.
        run: |
          cd $REPO_NAME

          docker build --tag sunwalker_box .
          id="$(docker create sunwalker_box .)"

          docker cp $id:/sunwalker_box sunwalker_box

      - name: Tests dependencies.
        run: |
          sudo apt install make python3.11 python3-yaml musl-tools libc6-dev
          sudo ln -sf /bin/python3.11 /bin/python3

      - name: Tests.
        run: |
          cd $REPO_NAME
          cat /proc/meminfo
          sudo make test

      - uses: actions/upload-artifact@master
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.REPO_NAME }}/sunwalker_box
